### PR TITLE
Updated versions of dependencies

### PR DESCRIPTION
**Pull request by miki-bgd**
Switched to Android v10.0 and Xamarin.Forms 5.0

### CODE REVIEW

**Comment by bojanmisic** [comment]
@stankonikolic Ready for Android 10 with XF 5.0 😁.

**Comment by bojanmisic** [comment]
@miki-bgd, tell me that this solves System.Numerics warnings, please!

**Comment by miki-bgd** [comment]
I would really want to...

**Comment by miki-bgd** [comment]
For reference:
> This build warning will go away when Xamarin transitions to One .NET, which is currently scheduled for .NET 6.

https://developercommunity.visualstudio.com/t/xamarin-found-conflicts-between-different-versions/788505

**Review by bojanmisic — APPROVED** [review]

**Pull request merged**
